name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/wc-deploy-cloudflare-pages.yml
    with:
      project-name: 'asis-docs'
      branch: 'staging'
      gh-app-id: ${{ vars.BOT_APP_ID }}
      pr-comment-enabled: false
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      gh-app-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
