name: 'Checks'

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed:
    uses: ./.github/workflows/wc-changed.yml

  check-actions:
    runs-on: ubuntu-24.04
    needs: changed
    if: needs.changed.outputs.actions == 'true'
    timeout-minutes: 10

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # https://github.com/marketplace/actions/actionlint-with-reviewdog
      - uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1.57.0
        with:
          fail_on_error: true
          filter_mode: nofilter
          level: error
          reporter: github-pr-review

  status-check:
    runs-on: ubuntu-24.04
    needs:
      - check-actions
    permissions: { }
    if: failure()
    steps:
      - run: exit 1
